language: node_js
node_js:
  - 0.12
before_install:
  - curl https://install.meteor.com/ | sh
  - npm install velocity-cli -g
script:
  - velocity test-app --once --ci
after_failure:
- "cat /home/travis/build/longuniquename/travis-test/.meteor/local/log/cucumber.log"
