language: node_js
node_js:
  - 0.12
before_install:
  - curl https://install.meteor.com/ | sh
  - npm install -g velocity-cli
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export PATH=$HOME/.meteor:$PATH"
  - "sleep 10"
script:
  - velocity test-app --once --ci
