language: node_js
node_js: "0.12.7"
before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm install -g velocity-cli
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export PATH=$HOME/.meteor:$PATH
  - sleep 10
env: JASMINE_SERVER_INTEGRATION=0 JASMINE_SERVER_UNIT=0 JASMINE_CLIENT_INTEGRATION=0 JASMINE_CLIENT_UNIT=0 CUCUMBER=1 VELOCITY_DEBUG=1 JASMINE_BROWSER=Firefox
script: velocity test-app --once --ci
after_failure: cat ./.meteor/local/log/cucumber.log
